language: fortran

env:
 - TEST_SUITE=RTI-LST/test_RTI.py
 - TEST_SUITE=RTI-LST/test_bound.py
 - TEST_SUITE=RTI-LST/test_restart.py
 - TEST_SUITE=RTI-LST/test_restart_long.py
 - TEST_SUITE=lid/test_lid.py
 - TEST_SUITE=iturb/test_iturb.py
 - TEST_SUITE=Hill/test_Hill.py
 - TEST_SUITE=duct/test_duct.py
 - TEST_SUITE=corner/test_corner.py
 - TEST_SUITE=eddy/test_eddy.py
 - TEST_SUITE=eddy/test_bdf2.py
 - TEST_SUITE=eddy/test_bdf3.py
 - TEST_SUITE=eddy/test_bdf4.py

before_install: 
 - mkdir -p $HOME/NekBox
 - mv * $HOME/NekBox
 - cd $HOME
 - sudo apt-get update -qq
 - sudo apt-get install -y mpich2 libmpich2-dev 
 - sudo apt-get install -y liblapack-dev
 - sudo apt-get install -y fftw3-dev
 - sudo apt-get install -y gfortran 
 - git clone https://github.com/maxhutch/nek-tests.git
 - git clone https://github.com/maxhutch/nek-tools.git
 - git clone https://github.com/maxhutch/nek-analyze.git
 - git clone -b async https://github.com/maxhutch/gslib.git
 - cd gslib
 - make
 - cd $HOME 

install:
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a
 - conda create -q -n test-environment python=3.4 numpy
 - source activate test-environment
 - conda install pytest chest cloudpickle
 - pip install graphviz mapcombine
 - pip install git+https://github.com/maxhutch/dask --upgrade
 - pip install git+https://github.com/maxhutch/nekpy --upgrade

script: 
 - if [ $TRAVIS_PULL_REQUEST -eq "false" ]; then py.test -v -m "not pr" nek-tests/$TEST_SUITE; else py.test -v nek-tests/$TEST_SUITE; fi
